echo "Uploading bloomfield patch"
python patch_upload.py 10.1.10.20 laundry.bin
echo "Uploaded to Laundry"
python patch_upload.py 10.1.10.18 church.bin
echo "Uploaded to Church"
python patch_upload.py 10.1.10.23 katmandu.bin
echo "Uplaoded to Katmandu"
python patch_upload.py 10.1.10.10 bank.bin
echo "Uploaded to Bank"
